/* Joins the modules in src/ into the one file Home Assistant loads.
 *
 * Deliberately not a bundler: the card has no dependencies, so "building" is
 * putting the modules behind each other in dependency order and dropping the
 * import and export keywords. Nothing is downloaded and nothing is transformed.
 *
 *   node build.mjs            write the card
 *   node build.mjs --check    fail when the committed card differs from src/
 *   node build.mjs --out <f>  write somewhere else
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

// Dependency order: a module only imports from modules above it.
const MODULES = ['format.js', 'i18n.js', 'pump.js', 'stats.js', 'model.js', 'editor.js', 'card.js'];

const DEFAULT_OUT = resolve(here, '../custom_components/renson_arean/frontend/renson-arean-card.js');

const IMPORT_LINE = /^import\s[^;]*\sfrom\s+'\.\/([\w-]+\.js)';\s*$/;
const MULTILINE_IMPORT = /^import\s*\{[^}]*\}\s*from\s+'\.\/([\w-]+\.js)';\n/gm;
const EXPORT_PREFIX = /^export\s+(?=(?:async\s+)?(?:const|let|function|class)\s)/;

function strip(name, seen) {
  const source = readFileSync(resolve(here, 'src', name), 'utf8');
  const imported = [];
  const withoutBlocks = source.replace(MULTILINE_IMPORT, (_match, from) => {
    imported.push(from);
    return '';
  });
  const lines = [];
  for (const line of withoutBlocks.split('\n')) {
    const single = line.match(IMPORT_LINE);
    if (single) {
      imported.push(single[1]);
      continue;
    }
    if (/^import\b/.test(line)) throw new Error(`${name}: unsupported import: ${line}`);
    if (/^export\b/.test(line) && !EXPORT_PREFIX.test(line)) {
      throw new Error(`${name}: unsupported export: ${line}`);
    }
    lines.push(line.replace(EXPORT_PREFIX, ''));
  }
  for (const from of imported) {
    if (!seen.has(from)) throw new Error(`${name} imports ${from}, which is not built before it`);
  }
  return lines.join('\n').trim();
}

export function build() {
  const seen = new Set();
  const parts = [];
  for (const name of MODULES) {
    parts.push(`  // ---- ${name} ----\n${strip(name, seen)}`);
    seen.add(name);
  }
  return [
    '/* Renson Arean dashboard card.',
    ' * Generated from frontend/src by frontend/build.mjs. Do not edit this file;',
    ' * edit the source and run the build. */',
    '(() => {',
    parts.join('\n\n'),
    '})();',
    '',
  ].join('\n');
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const outIndex = args.indexOf('--out');
  const out = outIndex >= 0 ? resolve(args[outIndex + 1]) : DEFAULT_OUT;
  const output = build();
  if (args.includes('--check')) {
    let current = null;
    try {
      current = readFileSync(out, 'utf8');
    } catch (_err) {
      // Reported below.
    }
    if (current !== output) {
      console.error(`${out} is not up to date with frontend/src. Run: node build.mjs`);
      process.exit(1);
    }
    console.log('Card is up to date.');
  } else {
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, output);
    console.log(`Wrote ${out} (${output.length} bytes)`);
  }
}
